name: drupal-amqp
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  composer_version: '2.0.7'
  database: mysql:5.7
  xdebug: true

# Set a reachable management site ( User: guest, Pass: guest )
proxy:
    rabbitmq:
      - rabbit.lndo.site:15672

# Setup RabbitMQ service using "compose"
services:
  rabbitmq:
    type: compose
    services:
     # Grab RabbitMQ management image
     image: "rabbitmq:management"
     hostname: "rabbit"

     # Start the server for RabbitMQ
     command: rabbitmq-server

     # Expose RabbitMQ Ports
     ports:
      - '15672:15672'
      - '5672:5672'

     # Link RabbitMQ Configs
     volumes:
      - rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
     labels:
       NAME: "rabbitmq"

  appserver:
    type: php:8.1
    build_as_root:
      - apt-get update -y
      - echo "Installing PHP extensions..."
      - docker-php-ext-install sockets
      - docker-php-ext-enable sockets
# Shows IP address on 'lando start'
events:
  post-start:
    - rabbitmq: echo -e "\n\e[36mRABBITMQ IP ADDRESS:\e[32m"
    - rabbitmq: hostname -i | cut -d' ' -f1
tooling:
  # Set up command "Lando rabbit" for basic RabbitMQ commands
  rabbit:
    service: rabbitmq
    # User must be root to prevent erlang cookie error
    user: root
    cmd: rabbitmqctl
  # Setup command "lando rabbit-ip" to get the ip address
  rabbit-ip:
    service: rabbitmq
    cmd:
      - echo -e "\n\e[36mRABBITMQ IP ADDRESS:\e[32m"
      - hostname -i | cut -d' ' -f1
