name: CI (with matrix)
on:
  workflow_dispatch:
jobs:
  test-suite:
    name: Test suite PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'ubuntu-18.04']
        php-versions: [ '7.4', '8.0', '8.1' ]
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP ${{ matrix.php-versions }} with Xdebug 3.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2
