name: CI
on:
  push:
  workflow_dispatch:
jobs:
  test-suite:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1 with Xdebug 3.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run test suite
        run: vendor/bin/phpunit -c phpunit.xml.dist --fail-on-incomplete  --coverage-clover clover.xml

      # https://github.com/marketplace/actions/codecov
      - name: Send test coverage to codecov.io
        uses: codecov/codecov-action@v2.1.0
        with:
          files: clover.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
